version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies
    target-branch: "main"
    pull-request-branch-name:
      separator: "/"

