version: '3.8'

services:
  webapi:
    restart: on-failure
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8004:8000"
    env_file:
      - .env
    depends_on:
      - webdb

  webdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - .env